[vc_row el_class=".block-width-header .text-align" css=".vc_custom_1477576935219{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_column css=".vc_custom_1477575252595{margin: 0px !important;padding: 0px !important;}"][/vc_column][/vc_row][vc_row][vc_column css=".vc_custom_1477056160887{padding-right: 0px !important;padding-left: 0px !important;}"][want_banner height="full" arrow="normal" arrow_tg=".arrow" arrow_speed="800" arrow_anim="yes" arrow_color="#2e2e2e" has_video="yes" vertical_align="vertical-middle" scroll_arrow="yes" overwrite="" banner_text_content="

" background_overlay="#9b9b9b" opacity_overlay="0.2" scroll_target=".text-teaser" video_mp4="app/uploads/videos/want_home.mp4" video_webm="app/uploads/videos/want_home.webm" video_ogg="app/uploads/videos/want_home.ogg"][vc_column_text el_class=".header-text" css=".vc_custom_1478259605288{margin-right: 10% !important;margin-left: 10% !important;}"]
<p style="width: 100%; color: #000000;">Goodyear Dunlop <span style="color: #000000;"> / Interaktives Online-Tool</span></p>
[/vc_column_text][/want_banner][/vc_column][/vc_row][vc_row el_class=".arrow"][vc_column][/vc_column][/vc_row][vc_row el_class=".block-width .block-height-1 .block-width-2-col"][vc_column width="1/3" css=".vc_custom_1478694943760{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}" el_class=".col-die-1"][vc_column_text el_class="title-sup"][/vc_column_text][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1478260151890{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]
<p class="font-size-075" style="text-align: left; padding-bottom: 10px;"><span style="color: #000000;">DIE
HERAUS-
FORDERUNG</span>

[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1478695785526{padding-top: 3px !important;}" el_class=".green-line-1200"][/vc_column][vc_column width="2/3" css=".vc_custom_1478694950930{margin-top: -5px !important;padding-top: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}" el_class=".col-die-2"][vc_column_text el_class="home-lato-regular-22-32 .padding-top-40"]<span style="text-align: left; padding: 0;"><span style="color: #000000;"><span class="home-lato-bold-22-32">Goodyear Dunlop Tires Germany GmbH</span> ist Hersteller von Autoreifen mit weltweit bekannten Marken.</span></span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32 .padding-top-33" css=".vc_custom_1480084320306{padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #000000; margin-left: -17px;">Unser Ziel:</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Entwicklung eines Business-Portals für die Zielgruppe <br class="br-delete" />Reifenhändler, das ein Prämiensystem einbindet</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Absatz der Autoreifen gezielt unterstützen</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Attraktives Tool für den Außendienst</span>[/vc_column_text][/vc_column][/vc_row][vc_row el_class=".block-height-328 scrollscene-dark-area" css=".vc_custom_1479032526279{background-color: #2c2c2c !important;}"][vc_column css=".vc_custom_1478697147869{padding-top: 0px !important;}"][vc_row_inner el_class=".block-width .pad-bot-120 .block-width-2-col"][vc_column_inner el_class=".col-die-1" width="1/3" css=".vc_custom_1478697190146{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1478262434926{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]

<p class="font-size-075" style="text-align: left; padding-bottom: 10px;"><span style="color: #ffffff;">INSIGHTS</span></p>
[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1478697167914{padding-top: 3px !important;}" el_class=".green-line-1200"][/vc_column_inner][vc_column_inner el_class=".col-die-2" width="2/3" css=".vc_custom_1478697196409{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32 .padding-top-40" css=".vc_custom_1480087810867{padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #ffffff;">Reifenhändler sind an Erfahrungsaustausch interessiert</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #ffffff;">Wünschen sich Support in Marketing, Verkauf und <br class="br-delete" />Fortbildung</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #ffffff;">Sind dankbar für sinnvolle Entlastung im Tagesgeschäft</span>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1478868843965{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;background-color: #f2f2f2 !important;}" el_class=".losung-small"][vc_column css=".vc_custom_1478863626698{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;background-color: #f2f2f2 !important;}"][vc_single_image image="3996" img_size="full" alignment="center" el_class=".losung-small"][/vc_column][/vc_row][vc_row css=".vc_custom_1478872495291{margin: 0px !important;padding: 0px !important;background-color: #f2f2f2 !important;}"][vc_column css=".vc_custom_1478872483483{margin: 0px !important;padding: 0px !important;}"][vc_row_inner el_class=".losung-big .block-width"][vc_column_inner el_class=".losung-col-1-new" width="1/2" css=".vc_custom_1478872816978{margin-top: -13.5px !important;}"][vc_single_image image="3998" img_size="full" el_class=".losung-img-1200" css=".vc_custom_1480685361777{margin-left: 0px !important;padding-left: 0px !important;}"][/vc_column_inner][vc_column_inner el_class=".losung-col-2-new" width="1/2" css=".vc_custom_1478872792764{margin-top: -13.5px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1477757167956{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 78.5px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]
<p style="text-align: left; padding-bottom: 10px;"><span style="color: #000000;">LÖSUNG</span></p>
[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1477757341965{padding-bottom: 32px !important;}"][vc_column_text el_class="home-lato-regular-22-32" css=".vc_custom_1477390196408{padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Relaunch des bestehenden Prämien-
systems als Businessportal</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Inhaltlich basierend auf drei Säulen:
<span class="home-lato-bold-22-32">Wissen &amp; Business, Prämienshop und
Trainingscenter</span></span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Innovativer Mehrwert:
Goodyear Dunlop unterstützt Reifen-
händler in ihrem kompletten Business
und geht in der Branche mit dieser
Lösung wegweisend voran.</span>
[/vc_column_text][vc_column_text css=".vc_custom_1480178875947{padding-top: 58px !important;padding-left: 28px !important;}"]<span class="home-lato-bold-22-32" style="color: #000000; margin-left: -28px;">&gt;&gt;</span> <span class="home-museo-slab700-22-32" style="color: #000000;">2-TÄGIGER WORKSHOP MIT HÄNDLERN, AUSSENDIENST, MARKETING UND AGENTUR!</span>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".losung-320-img .losung-320-bg" css=".vc_custom_1480686463269{background-color: #f2f2f2 !important;}"][vc_column css=".vc_custom_1480685471960{padding-top: 0px !important;}"][vc_single_image image="4002" img_size="full" alignment="center" el_class=".losung-320-img .losung-320-bg"][/vc_column][/vc_row][vc_row el_class=".losung-320-text block-width"][vc_column css=".vc_custom_1480088522704{margin-right: 0px !important;margin-left: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1480090146116{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 33.5px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]
<p style="text-align: left; padding-bottom: 10px;"><span style="color: #000000;">LÖSUNG</span></p>
[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1480090259675{padding-bottom: 20px !important;}"][vc_column_text el_class="home-lato-regular-22-32" css=".vc_custom_1480090923710{padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Relaunch des bestehenden Prämien-<br class="br-delete" />systems als Businessportal</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Inhaltlich basierend auf drei Säulen: <br class="br-delete" /><span class="home-lato-bold-22-32">Wissen &amp; Business, Prämienshop und <br class="br-delete" />Trainingscenter</span></span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Innovativer Mehrwert: <br class="br-delete" />Goodyear Dunlop unterstützt Reifen-<br class="br-delete" />händler in ihrem kompletten Business <br class="br-delete" />und geht in der Branche mit dieser <br class="br-delete" />Lösung wegweisend voran.</span>[/vc_column_text][vc_column_text css=".vc_custom_1480178946122{padding-top: 18px !important;padding-left: 26px !important;}" el_class=".font-losung-320"]<span class="font-losung-320" style="color: #000000; margin-left: -26px;">&gt;&gt;</span> <span class="font-losung-320" style="color: #000000;">2-TÄGIGER WORKSHOP MIT HÄNDLERN, AUSSENDIENST, MARKETING UND AGENTUR!</span>[/vc_column_text][/vc_column][/vc_row][vc_row el_class=".block-width .block-height-691 .umsetzung-768 .block-width-umset" css=".vc_custom_1480177209764{margin-bottom: 0px !important;padding-bottom: 115px !important;}"][vc_column width="1/2" css=".vc_custom_1478866789363{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}" el_class=".col-480"][vc_column_text el_class="title-sup"][/vc_column_text][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1478262444053{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]
<p class="font-size-075" style="text-align: left; padding-bottom: 10px;"><span style="color: #000000;">UMSETZUNG</span></p>
[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1478112439655{padding-top: 3px !important;}"][vc_column_text el_class="home-lato-regular-22-32" css=".vc_custom_1478711481213{padding-top: 22px !important;padding-bottom: 25px !important;}"]<span class="home-museo-slab700-22-32 home-museo-slab700-18-27" style="color: #000000;">BUSINESSPORTAL MIT
INCENTIVIERUNG FÜR
HÄNDLER
</span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32 .padding-top-19" css=".vc_custom_1478815027750{padding-bottom: 0px !important;padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Aufgabenbezogene Informationsarchitektur</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Starker Tool-Charakter auf allen Endgeräten</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Redaktioneller Content zur unternehmerischen</span>
<span style="color: #000000;">Unterstützung des Reifenhändlers</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Prämiensystem und E-Learning-Center</span>[/vc_column_text][/vc_column][vc_column width="1/2" css=".vc_custom_1478866959749{margin-bottom: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}" el_class=".col-480-2"][vc_raw_html css=".vc_custom_1478714143412{padding-top: 17px !important;}"]JTNDaW1nJTIwc3JjJTNEJTIyJTJGYXBwJTJGdXBsb2FkcyUyRjIwMTYlMkYxMCUyRkxZLVdBTlRfV2Vic2l0ZV8xNjA5MjUucG5nJTIyJTIwY2xhc3MlM0QlMjJ2Y19zaW5nbGVfaW1hZ2UtaW1nJTIwYXR0YWNobWVudC1mdWxsJTIwc2lkZS1ieS1zaWRlLWltZyUyMGltZy03NjglMjIlMjBhbHQlM0QlMjJQZ2VfNVdBTlRfV2Vic2l0ZV8xNjA5MjMlMjIlMjB3aWR0aCUzRCUyMjEwMTMlMjIlMjBoZWlnaHQlM0QlMjI2ODMlMjIlM0U=[/vc_raw_html][/vc_column][/vc_row][vc_row el_class=".block-width .block-height-691 .umsetzung-320" css=".vc_custom_1480092643540{margin-bottom: 0px !important;padding-bottom: 30px !important;}"][vc_column width="1/2" css=".vc_custom_1478866789363{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}" el_class=".col-480"][vc_single_image image="2711" img_size="full" alignment="center"][/vc_column][vc_column width="1/2" css=".vc_custom_1478866959749{margin-bottom: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}" el_class=".col-480-2"][vc_column_text el_class="home-museo-slab700-50-50 .umsetzung-480-pad" css=".vc_custom_1480675228640{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]
<p class="font-size-075" style="text-align: left; padding-bottom: 10px;"><span style="color: #000000;">UMSETZUNG</span></p>
[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1478112439655{padding-top: 3px !important;}"][vc_column_text el_class="home-lato-regular-22-32" css=".vc_custom_1480092743415{padding-top: 12px !important;padding-bottom: 15px !important;}"]<span class="home-museo-slab700-22-32 home-museo-slab700-18-27" style="color: #000000;">BUSINESSPORTAL MIT <br class="br-delete" />INCENTIVIERUNG FÜR <br class="br-delete" />HÄNDLER
</span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32 .padding-top-19" css=".vc_custom_1480092825506{padding-bottom: 0px !important;padding-left: 17px !important;}"]<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Aufgabenbezogene Informationsarchitektur</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Starker Tool-Charakter auf allen Endgeräten</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Redaktioneller Content zur unternehmerischen</span> <br class="br-delete" /><span style="color: #000000;">Unterstützung des Reifenhändlers</span>
<span class="home-lato-heavy-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Prämiensystem und E-Learning-Center</span>[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1480094557765{background-color: #2c2c2c !important;}" el_class=".block-height-896 .padding-top-112 scrollscene-dark-area"][vc_column css=".vc_custom_1479986131551{margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1478811476440{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 6px !important;padding-left: 0px !important;}"]

<p style="padding-bottom: 10px; text-align: center;"><span style="color: #ffffff; font-size: 50px; line-height: 50px;">LOGO &amp; CI
RELAUNCH</span>

[/vc_column_text][vc_single_image image="1913" img_size="full" alignment="center" el_class=".green-line-tir-bot"][vc_single_image image="2684" img_size="full" alignment="center" css=".vc_custom_1480093559632{margin-top: -6px !important;margin-bottom: 0px !important;padding-bottom: 0px !important;}" el_class=".img-block-width-1"][vc_row_inner css=".vc_custom_1477759414507{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column_inner css=".vc_custom_1477759393433{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_single_image image="2733" img_size="full" alignment="center" el_class=".img-block-width"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".block-height-386 block-width-695 block-6-768"][vc_column width="1/3" css=".vc_custom_1479476869921{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}" el_class=".relevante-col-1"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1479476136338{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Relevante Inhalte</span>
für Unternehmer</span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32-1 pad-top-54 pad-top-320-2" css=".vc_custom_1480099662364{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Ganzheitliche Unterstützung</span> als
Kundenbindungsmittel</span>[/vc_column_text][/vc_column][vc_column width="1/3" el_class=".relevante-col-2" css=".vc_custom_1479476877424{padding-top: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1 pad-top-320-2" css=".vc_custom_1480099650594{padding-top: 0px !important;padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Produkttrainings
&amp; E-Learnings</span></span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32-1 pad-top-54" css=".vc_custom_1479478082646{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Multifunktionales
<span style="font-weight: bold;">Dashboard</span></span>[/vc_column_text][/vc_column][vc_column width="1/3" el_class=".relevante-col-3" css=".vc_custom_1479479146086{margin-right: -5px !important;padding-top: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1480756243568{margin-right: -2px !important;padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Incentivierung</span>
durch den Außendienst</span>[/vc_column_text][vc_column_text el_class="home-lato-regular-22-32-1 pad-top-54 pad-top-320-2" css=".vc_custom_1480099674459{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Redaktioneller
Content</span> als
Vertriebstool</span>[/vc_column_text][/vc_column][/vc_row][vc_row el_class="block-width block-6-320"][vc_column css=".vc_custom_1480179727634{padding-right: 0px !important;padding-left: 0px !important;}"][vc_row_inner css=".vc_custom_1480095868704{margin-right: 0px !important;margin-left: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480179746820{margin-left: 0px !important;padding-right: 30px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1479476136338{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Relevante Inhalte</span>
für Unternehmer</span>[/vc_column_text][/vc_column_inner][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480096274883{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1480180146643{margin-right: -3px !important;padding-top: 0px !important;padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Produkttrainings <br class="br-delete" />&amp; E-Learnings</span></span>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".row-6-pad-top" css=".vc_custom_1480098505501{margin-right: 0px !important;margin-left: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480096774309{margin-right: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 30px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1479476309058{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Incentivierung</span>
durch den Außendienst</span>[/vc_column_text][/vc_column_inner][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480096286238{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1 .pad-top-320-2" css=".vc_custom_1480179829771{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Ganzheitliche Unterstützung</span> <br class="br-delete" />als <br class="br-delete" />Kundenbindungsmittel</span>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".row-6-pad-top-19" css=".vc_custom_1480098694030{margin-right: 0px !important;margin-left: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480096782231{margin-right: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 30px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1" css=".vc_custom_1480096006024{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;">Multifunktionales
<span style="font-weight: bold;">Dashboard</span></span>[/vc_column_text][/vc_column_inner][vc_column_inner el_class="col-6-320" width="1/2" css=".vc_custom_1480096293125{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-lato-regular-22-32-1 .pad-top-320-2" css=".vc_custom_1480676085573{padding-left: 17px !important;}"]<span class="home-lato-regular-22-32" style="color: #00ff00; margin-left: -17px;">&gt;</span> <span style="color: #000000;"><span style="font-weight: bold;">Redaktioneller
Content</span> als <br class="br-delete" />Vertriebstool</span>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1480100455722{background-color: #f4f4f4 !important;}" el_class=".block-height-2660"][vc_column css=".vc_custom_1477231152693{margin-top: 0px !important;padding-top: 0px !important;}"][vc_single_image image="2712" img_size="full" alignment="center" el_class=".img-1"][vc_single_image image="2714" img_size="full" alignment="center" el_class=".img-2"][vc_single_image image="2715" img_size="full" alignment="center" el_class=".img-3"][vc_single_image image="2716" img_size="full" alignment="center" el_class=".img-4"][/vc_column][/vc_row][vc_row css=".vc_custom_1477574170640{margin-top: -3px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;background-color: #f4f4f4 !important;}"][vc_column css=".vc_custom_1477573831272{margin: 0px !important;padding: 0px !important;}"][vc_raw_html el_class="want-logo"]JTNDYSUyMGhyZWYlM0QlMjJodHRwJTNBJTJGJTJGdy1hLW4tdC5kZSUyRiUyMiUyMCUzRSUwQSUyMCUyMCUyMCUyMCUzQ2ltZyUyMHNyYyUzRCUyMmh0dHAlM0ElMkYlMkZ3LWEtbi10LmRlJTJGYXBwJTJGdGhlbWVzJTJGc2FnZSUyRmxvZ28ucG5nJTIyJTIwYWx0JTNEJTIyJTIyJTIwd2lkdGglM0QlMjIlMjIlMjBoZWlnaHQlM0QlMjIlMjIlM0UlMEElM0MlMkZhJTNF[/vc_raw_html][/vc_column][/vc_row]