[vc_row][vc_column][want_banner bg_type="video" volume_ctrl="yes" volume="30" bg_ovrl="yes" bg_ovr_color="#574644" bg_ovrl_opacity="0.2" height="full" valign="middle" arrow="normal" arrow_tg=".block-height-238" arrow_speed="800" arrow_anim="yes" arrow_color="" has_video="yes" vertical_align="vertical-middle" scroll_arrow="yes" overwrite="" banner_text_content="

" background_overlay="#9b9b9b" opacity_overlay="0.2" scroll_target=".text-teaser" video_mp4="app/uploads/videos/want_home.mp4" video_webm="app/uploads/videos/want_home.webm" video_ogg="app/uploads/videos/want_home.ogg" poster="1527" mp4_url="app/uploads/videos/want_home.mp4" webm_url="app/uploads/videos/want_home.webm" ogg_url="app/uploads/videos/want_home.ogg"][vc_single_image image="1842" img_size="full" alignment="center" el_class="home-logo-img" css=".vc_custom_1479735699593{padding-bottom: 19px !important;}"][/want_banner][/vc_column][/vc_row][vc_row el_class=".weil-block block-width"][vc_column width="1/2" css=".vc_custom_1479736900423{margin-top: -5px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}" el_class="weil-col-1"][vc_column_text el_class="home-lato-regular-22-32" css=".vc_custom_1476962537653{margin-top: -3px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]

WARUM DIALOG-KOMMUNIKATION?

[/vc_column_text][vc_column_text el_class="title-sup"][/vc_column_text][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1476962510807{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"]

WEIL PUSH
NICHT ZIEHT!

[/vc_column_text][vc_single_image image="1913" img_size="full" el_class=".pad-bot-25 .green-line-1200"][/vc_column][vc_column width="1/2" css=".vc_custom_1479798261509{padding-right: 0px !important;padding-left: 0px !important;}" el_class=".zuh-col-2-test"][vc_column_text el_class="home-lato-regular-22-32"]

Nachhaltige Kundenbindung und hohe Conver­sion-Raten – beides braucht starke Pull-Effekte und Involvement. Genau darauf zielen unsere Lösungen ab. Ob Vertrieb oder Kunde, ob Mitarbeiter oder Multiplikatoren: Wir machen Ihre Zielgruppen zu Dialogpartnern, die sich aktiv in die Kommunikation einbringen.

[/vc_column_text][/vc_column][/vc_row][vc_row el_class=".block-height-807 scrollscene-dark-area .das-ist-1200" css=".vc_custom_1479817835459{background-color: #262626 !important;}"][vc_column css=".vc_custom_1478675170099{padding-top: 0px !important;}"][vc_row_inner el_class=".block-width .das-ist-padding .block-width-das-ist"][vc_column_inner el_class=".col-1 .right-align-design-fix" width="1/3" css=".vc_custom_1479835360533{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1477990190940{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 11px !important;padding-left: 0px !important;}"]DAS IST
UNSER
JOB[/vc_column_text][vc_single_image image="1913" img_size="full" el_class=".green-line-1200"][/vc_column_inner][vc_column_inner el_class=".col-2" width="1/3" css=".vc_custom_1479739649646{margin-top: -7px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 padding-top-analyse-50-1"]ANALYSE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32 font-size" css=".vc_custom_1479745062875{padding-left: 17px !important;}"]> Zielgruppe und
Aufgabe fokussieren
> Workshop
> Interview
> Online-Befragung[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-3" width="1/3" css=".vc_custom_1479739656696{margin-top: -7px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-analyse-50-2"]STRATEGIE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1480070868319{padding-left: 17px !important;}"]> Dialog-Strategie
> Touchpoint-Strategie
> Kommunikations-Strategie
> Informationsarchitektur
[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".block-width .block-width-das-ist"][vc_column_inner el_class=".col-1 .right-align-design-fix" width="1/3"][/vc_column_inner][vc_column_inner el_class=".col-2" width="1/3" css=".vc_custom_1479740787691{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]BRAND[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1478022314580{padding-bottom: 10px !important;padding-left: 17px !important;}"]> Markenentwicklung
> Corporate Identity
> Corporate Design
> Corporate Language[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-3" width="1/3" css=".vc_custom_1479740795042{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]ONLINE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1478022307264{padding-bottom: 10px !important;padding-left: 17px !important;}"]> Content
> Community/Portal
> Online-Tool
> Website/Microsite[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".block-width .padding-bt-40 .block-width-das-ist"][vc_column_inner el_class=".col-1 .right-align-design-fix" width="1/3"][/vc_column_inner][vc_column_inner el_class=".col-2" width="1/3" css=".vc_custom_1479740806099{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]FILM[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1477898893062{padding-left: 17px !important;}"]> Imagefilm
> Erklärfilm
> 360°-Film[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-3" width="1/3" css=".vc_custom_1479740813587{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]IMPLEMENTIERUNG[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1479741246805{padding-left: 17px !important;}"]> Multikanal
> Produktion
> Programmierung[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".block-height-807-320 scrollscene-dark-area .das-ist-copy" css=".vc_custom_1479818289099{background-color: #262626 !important;}"][vc_column css=".vc_custom_1478675170099{padding-top: 0px !important;}"][vc_row_inner el_class=".block-width .das-ist-padding"][vc_column_inner el_class=".col-320-1" width="1/2" css=".vc_custom_1479812453383{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-50-50" css=".vc_custom_1477990190940{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 11px !important;padding-left: 0px !important;}"]DAS IST
UNSER
JOB[/vc_column_text][vc_single_image image="1913" img_size="full" el_class=".green-line-1200"][/vc_column_inner][vc_column_inner el_class=".col-320-2" width="1/2" css=".vc_custom_1479812462729{margin-top: -7px !important;padding-right: 0px !important;padding-left: 0px !important;}"][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".block-width"][vc_column_inner el_class=".col-320-1" width="1/2"][vc_column_text el_class="home-museo-slab700-22-32 padding-top-analyse-50-1"]ANALYSE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32 font-size" css=".vc_custom_1479745062875{padding-left: 17px !important;}"]> Zielgruppe und
Aufgabe fokussieren
> Workshop
> Interview
> Online-Befragung[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-320-2" width="1/2" css=".vc_custom_1479814006738{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 padding-top-analyse-50-2"]STRATEGIE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1480071106907{padding-left: 17px !important;}"]> Dialog-Strategie
> Touchpoint-Strategie
> Kommunikations-
Strategie
> Informationsarchitektur[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".block-width"][vc_column_inner el_class=".col-320-1" width="1/2"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]BRAND[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1478022314580{padding-bottom: 10px !important;padding-left: 17px !important;}"]> Markenentwicklung
> Corporate Identity
> Corporate Design
> Corporate Language[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-320-2" width="1/2" css=".vc_custom_1479814267362{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]ONLINE[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1478022307264{padding-bottom: 10px !important;padding-left: 17px !important;}"]> Content
> Community/Portal
> Online-Tool
> Website/Microsite[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class=".block-width" css=".vc_custom_1480161510363{padding-bottom: 47px !important;}"][vc_column_inner el_class=".col-320-1" width="1/2"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]FILM[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1477898893062{padding-left: 17px !important;}"]> Imagefilm
> Erklärfilm
> 360°-Film[/vc_column_text][/vc_column_inner][vc_column_inner el_class=".col-320-2" width="1/2" css=".vc_custom_1479814257919{padding-right: 0px !important;padding-left: 0px !important;}"][vc_column_text el_class="home-museo-slab700-22-32 .padding-top-50"]IMPLEMENTIERUNG[/vc_column_text][vc_column_text el_class="home-lato-medium-22-32" css=".vc_custom_1479741246805{padding-left: 17px !important;}"]> Multikanal
> Produktion
> Programmierung[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".slider-height .slider-768-1280" css=".vc_custom_1479750460801{background-color: #f9f9f9 !important;}"][vc_column css=".vc_custom_1479746385267{padding-top: 0px !important;}"][vc_row_inner el_class="block-width-slider block-width" css=".vc_custom_1479913714915{padding-top: 0px !important;}"][vc_column_inner css=".vc_custom_1479746241154{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_images_carousel images="2777" img_size="full" onclick="custom_link" el_class=".slider-style .img-size block-width block-width-slider .slider-height" css=".vc_custom_1479913900364{background-color: #f9f9f9 !important;}" custom_links="#E-8_aHR0cCUzQSUyRiUyRnRlc3QtbnVyLXRlc3QuZGUlMkZpbnNpZ2h0cyUyRg=="][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".slider-height .slider-320" css=".vc_custom_1479750818506{background-color: #f9f9f9 !important;}"][vc_column css=".vc_custom_1479819466213{padding-top: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_row_inner el_class="block-width" css=".vc_custom_1479746251049{padding-top: 0px !important;}"][vc_column_inner css=".vc_custom_1479746241154{margin-top: 0px !important;margin-right: 0px !important;margin-bottom: 0px !important;margin-left: 0px !important;padding-top: 0px !important;padding-right: 0px !important;padding-bottom: 0px !important;padding-left: 0px !important;}"][vc_single_image image="3661" img_size="full" alignment="center" onclick="custom_link" link="http://test-nur-test.de/insights/" css=".vc_custom_1479750884196{padding-top: 20px !important;}"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class=".slider-320 .block-width" css=".vc_custom_1479912054263{margin-top: 0px !important;margin-bottom: 0px !important;padding-top: 0px !important;padding-bottom: 0px !important;}"][vc_column css=".vc_custom_1479750692132{margin: 0px !important;padding: 0px !important;}"][vc_single_image image="3662" img_size="full" onclick="custom_link" link="http://test-nur-test.de/insights/" css=".vc_custom_1479911938573{padding-top: 12px !important;}"][/vc_column][/vc_row][vc_row el_class="home-museo-slab700-50-50 .block-width .pad-top-116"][vc_column css=".vc_custom_1476785233360{padding-left: 0px !important;}"][vc_column_text css=".vc_custom_1476787989932{padding-bottom: 19px !important;}"]

WANT
KUNDEN

[/vc_column_text][vc_single_image image="1913" img_size="full" css=".vc_custom_1479805134215{padding-top: 0px !important;}" el_class=".green-line-1200"][/vc_column][vc_column css=".vc_custom_1478105576311{margin-top: -43px !important;padding-top: 0px !important;padding-right: 0px !important;padding-left: 0px !important;}"][vc_single_image image="3012" img_size="full" alignment="center" el_class=".bott-img-padding"][/vc_column][/vc_row][vc_row][vc_column][vc_raw_js]JTNDc2NyaXB0JTIwdHlwZSUzRCUyMnRleHQlMkZqYXZhc2NyaXB0JTIyJTNFJTBBY29uc29sZS5sb2clMjglMjJ0aGlzJTIwaXMlMjBqcyUyMiUyOSUzQiUwQSUzQyUyRnNjcmlwdCUzRQ==[/vc_raw_js][/vc_column][/vc_row]